# Generated by Django 4.1.4 on 2022-12-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextblog_app', '0002_alter_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog',
            field=models.TextField(max_length=5000),
        ),
    ]
